### ISSUE TITLE
Integer length bug.

### ISSUE THREAD

**Issue by fortmarek** [Vaultio/EtherKit#33] opened 2018-09-10 13:55 UTC
I have this code:
``` swift 
let helloIntEightFunctionCall = Function(name: "helloIntEight", parameters: [Int(8)])
let helloIntEightData = GeneralData(data: helloIntEightFunctionCall.encodeToCall())
self.etherQuery.send(using: using, to: self.at, value: amount, data: helloIntEightData, completion: { result in
                    switch result {
                    case .success(let hash):
                        observer.send(value: hash)
                    case .failure(let error):
                        observer.send(error: error)
                        observer.sendCompleted()
                    }
                })
```
My contract function expects `int8`.
This code fails with this message: "gas required exceeds allowance or always failing transaction"

However, if I change the value of size to 8 in `ABI.swift` like this:
```swift 
extension Int: ABIValueType {
  public var abiType: ABIType {
    return .int(size: 8, value: BigInt(self))
  }
}
```

Then calling the function succeeds. If this is not a bug, how should I change my code for it to work?

Thanks,
Marek from Ackee

**Comment by SirensOfTitan** [comment] 2018-09-13 16:40
@pr0zac : thoughts here?

**Comment by pr0zac** [comment] 2018-09-14 17:44
The issue is Ints are encoded to int64 because thats what they represent in Swift. I'll add ABIValueTypes for the other Int/UInt Swift types, once that lands you should be able to do:
```let helloIntEightFunctionCall = Function(name: "helloIntEight", parameters: [Int8(8)])``` and it will encode correctly.

**Comment by pr0zac** [comment] 2018-09-14 18:32
Ok, I made the changes I mentioned in the latest commit and its been landed on master. You should be able to use it as I described now!

**Closed by pr0zac** 2018-09-14 18:32 UTC
